Vision360/RestaurantBooking/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vision360/core/urls.py
from django.urls import path
from .views import homeView, login_view, logout_view, inicio_view,  lista_facultades, lista_carreras, registrar_carrera, registrar_facultad, listar_bloques, registrar_bloque, bloques_carrera
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('inicio/', homeView, name="page-home"),
    path('', inicio_view, name="page-comenzar"),
    path('login/', login_view, name="page-login"),
    path('logout/', logout_view, name='page-logout'),
    path('facultades/', lista_facultades, name='page-facultades'),
    path('carreras/', lista_carreras, name='page-carreras'),
    path('bloques/', listar_bloques, name='page-bloques'),
    path('nueva-carrera/', registrar_carrera, name="registrar-carrera"),
    path('nueva-facultad/', registrar_facultad, name="registrar-facultad"),
    path('nuevo-bloque/', registrar_bloque, name="registrar-bloque"),


    
    path('carrera/<int:carrera_id>/bloques/', bloques_carrera, name='bloques_carrera'),





   

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Vision360/core/models.py
# En tu archivo models.py

from django.db import models
from django.utils import timezone

class Facultad(models.Model):
    nombre = models.CharField(max_length=100)
    siglas = models.CharField(max_length=100)
    ubicacion = models.URLField(blank=True)
    date_joined = models.DateTimeField(default=timezone.now, editable=False)


    def __str__(self):
        return self.nombre

class Carrera(models.Model):
    nombre = models.CharField(max_length=100)
    semestres = models.IntegerField()
    facultad = models.ForeignKey(Facultad, on_delete=models.CASCADE)
    recorrido = models.BooleanField(default=False)
    date_joined = models.DateTimeField(default=timezone.now, editable=False)

    def __str__(self):
        return self.nombre

class Bloque(models.Model):
    codigo_identificativo= models.CharField(max_length=10)
    nombre = models.CharField(max_length=100)
    carrera = models.ForeignKey(Carrera, on_delete=models.CASCADE)
    descripcion = models.TextField()
    estado = models.BooleanField(default=True)  # Campo booleano para el estado, por defecto True (activo)
    imagen = models.ImageField(upload_to='media/bloque_fotos/')  # Directorio donde se guardarán las imágenes
    link = models.URLField(blank=True)  # Campo para el enlace, puede estar vacío

    def __str__(self):
        return self.nombre

Vision360/core/forms.py
from django import forms
from .models import Carrera, Facultad, Bloque

class CarreraForm(forms.ModelForm):
    class Meta:
        model = Carrera
        fields = ['nombre', 'semestres', 'facultad', 'recorrido']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'semestres': forms.NumberInput(attrs={'class': 'form-control'}),
            'facultad': forms.Select(attrs={'class': 'form-control'}),
            'recorrido': forms.RadioSelect(choices=((True, 'Sí'), (False, 'No')), attrs={'class': 'form-check-input'})
        }


class FacultadForm(forms.ModelForm):
    class Meta:
        model = Facultad
        fields = ['nombre', 'siglas', 'ubicacion']
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'siglas': forms.TextInput(attrs={'class': 'form-control'}),
            'ubicacion': forms.URLInput(attrs={'class': 'form-control'}),
        }


class BloqueForm(forms.ModelForm):
    class Meta:
        model = Bloque
        fields = ['codigo_identificativo','nombre', 'carrera', 'descripcion', 'estado', 'imagen', 'link']
        widgets = {
            'codigo_identificativo': forms.TextInput(attrs={'class': 'form-control'}),
            'nombre': forms.TextInput(attrs={'class': 'form-control'}),
            'carrera': forms.Select(attrs={'class': 'form-control'}),
            'descripcion': forms.Textarea(attrs={'class': 'form-control'}),
            'estado': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'imagen': forms.FileInput(attrs={'class': 'form-control-file'}),
            'link': forms.URLInput(attrs={'class': 'form-control'})
        }

Vision360/core/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.template.loader import get_template
from django.views.generic import DetailView, View
from datetime import date
from django.contrib import messages
from .models import Facultad, Carrera, Bloque
from .forms import CarreraForm, FacultadForm, BloqueForm
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import permission_required

 


def homeView (request):
    user = request.user
    carreras = Carrera.objects.filter(recorrido=True).distinct()
    
    if user.is_superuser:
        contexto = {
            'user': user,
            }
        return render(request, "RestaurantBooking/PageUtils/home-admin.html", contexto)
    else:
        contexto = {
            'carreras': carreras
            }
        return render(request, "RestaurantBooking/PageUtils/home-user.html", contexto)

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('page-home')
        else:
            error_message = 'Existe un error las con crendenciales.'
            return render(request, 'RestaurantBooking/PageUtils/login.html', {'error_message': error_message})
    else:
        return render(request, 'RestaurantBooking/PageUtils/login.html')

def logout_view(request):
    logout(request)
    # Redirecciona a la página de inicio o a donde desees después de cerrar sesión
    return redirect('page-login')

@permission_required('auth.is_superuser')
def lista_facultades(request):
    facultades = Facultad.objects.all()
    return render(request, 'RestaurantBooking/PagesFacultades/facultades.html', {'facultades': facultades})

@permission_required('auth.is_superuser')
def registrar_facultad(request):
    if request.method == 'POST':
        form = FacultadForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('page-facultades')  # Reemplaza 'nombre_de_la_url' con el nombre de la URL de la página de inicio
    else:
        form = FacultadForm()
    return render(request, 'RestaurantBooking/PagesFacultades/nueva-facultad.html', {'form': form})

@permission_required('auth.is_superuser')
def lista_carreras(request):
    carreras = Carrera.objects.all()
    return render(request, 'RestaurantBooking/PagesFacultades/carreras.html', {'carreras': carreras})

@permission_required('auth.is_superuser')
def registrar_carrera(request):
    if request.method == 'POST':
        form = CarreraForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('page-carreras')  # Reemplaza 'nombre_de_la_url' con el nombre de la URL de la página de inicio
    else:
        form = CarreraForm()
    return render(request, 'RestaurantBooking/PagesFacultades/nueva-carrera.html', {'form': form})

@permission_required('auth.is_superuser')
def listar_bloques(request):
    bloques = Bloque.objects.all()
    return render(request, 'RestaurantBooking/PagesFacultades/bloques.html', {'bloques': bloques})

@permission_required('auth.is_superuser')
def registrar_bloque(request):
    if request.method == 'POST':
        form = BloqueForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            form.save()
            return redirect('page-bloques')  # Redirige a la página de lista de bloques
    else:
        form = BloqueForm()
    return render(request, 'RestaurantBooking/PagesFacultades/nuevo-bloque.html', {'form': form})


def bloques_carrera(request, carrera_id):
    # Obtener la carrera específica o devolver un error 404 si no existe
    carrera = get_object_or_404(Carrera, id=carrera_id)
    carreras = Carrera.objects.filter(recorrido=True).distinct()
    
    # Filtrar los bloques asociados a la carrera
    bloques = Bloque.objects.filter(carrera=carrera)
    
    contexto = {
        'carrera': carrera,
        'bloques': bloques,
        'carreras': carreras
    }
    return render(request, "RestaurantBooking/PagesFacultades/bloques-carrera.html", contexto)


def inicio_view (request):
    return render (request,"RestaurantBooking/PageUtils/inicio.html")

Vision360/core/templates/RestaurantBooking/PagesFacultades/bloques-carrera.html
{% extends 'RestaurantBooking/PageUtils/base-user.html' %}

{% block content %}

{% if bloques %}
<div class="alert alert-info" role="alert">
    Agradecemos tu visita en esta sección tienes a tu disponibilidad todos los bloques de la carrera {{carrera.nombre}}
  </div>
<section  class="border rounded">
    <div class="container py-5">
        {% for item in bloques %}
      <div class="row justify-content-center mb-3">
        <div class="col-md-12 col-xl-10" >
          <div class="card shadow-0 border rounded-3"  style="background-color: #e0e0e0;">
            <div class="card-body">
              <div class="row">
                <div class="col-md-12 col-lg-3 col-xl-3 mb-4 mb-lg-0">
                  <div class="bg-image hover-zoom ripple rounded ripple-surface">
                    <img src="{{item.imagen.url}}"
                      class="rounded border" width="140px"/>
                    <a href="#!">
                      <div class="hover-overlay">
                        <div class="mask" style="background-color: rgba(253, 253, 253, 0.15);"></div>
                      </div>
                    </a>
                  </div>
                </div>
                <div class="col-md-6 col-lg-6 col-xl-6">
                  <spam class="text-dark">Bloque: {{item.codigo_identificativo}} >> {{item.nombre}} </spam>
                  <div class="d-flex flex-row">
                    <div class="text-warning mb-1 me-2">
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                      <i class="fa fa-star"></i>
                    </div>
                  </div>
                  
                  <div class="mb-2 text-muted small">
                    <span>Universidad Nacional de Loja</span>
                    <span> Ciudad Universitaria </span>
                    <span>Guillermo Falconi</span>
                    
                  </div>
                  <p class="text-truncate mb-4 mb-md-0">
                    <spam class="text-dark">Descripción: </spam>{{item.descripcion}}
                  </p>
                </div>
                <div class="col-md-6 col-lg-3 col-xl-3 border-sm-start-none border-start">
                  <div class="alert alert-warning mb-2 text-muted small">
                    <spam>Dale clik al botón verde y visita este bloque</spam>

                  </div>
                  <div class="d-flex flex-column mt-4 ml-4">
                    <a target="_blank" href="{{item.link}}"><button class="btn btn-success btn-sm" type="button">Realiza recorrido <i class="fas fa-plane"></i></button></a>

                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
{% else %}
<div style="text-align: center;">
    <div class="alert alert-danger" role="alert" style="margin-bottom: 20px;">
        La carrera {{ carrera.nombre }} no cuenta con bloques que permitan una visita en 360.
    </div>
    <div id="error-container" style="margin-bottom: 20px;">
        <h1 style="color: red;">Error 404: Página no encontrada</h1>
        <p>Lo sentimos, la página que estás buscando no se ha encontrado.</p>
        <p>Por favor, contacta a nuestro servicio al cliente para obtener ayuda.</p>
        <button onclick="window.history.back()" class="btn btn-warning">Regresar</button>
    </div>
    <p style="font-style: italic; color: green;">¡Gracias por visitarnos!</p>
</div>


{% endif %}

{% endblock%}

Vision360/core/templates/RestaurantBooking/PagesFacultades/bloques.html
{% extends 'RestaurantBooking/PageUtils/base.html'%}

{% block content %}
<div class="card shadow mb-4">
    <div class="end">
        <div class="alert alert-warning">
            <p>Para registrar un nuevo bloque, navega hasta el menú ubicado al lado izquierdo <spam style="font-style: oblique; color: black;">(Gestión Bloques > Nuevo Bloque),</spam>  haz clic, llena el formulario y listo.</p>
        </div>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead" style="background-color: #111927; color: aliceblue;">
                    <tr>
                        <th>Bloque</th>
                        <th>Carrera</th>
                        <th>Facultad</th>
                        <th>Descripción</th>
                        <th>Link (Recorrido Virtual)</th>
                        <th>Estado</th>
                        <th>Imágenes</th>
                        <th>Opciones</th>

                    </tr>
                </thead>
                <tbody>
                    {% for bloque in bloques %}
                    <tr>
                        <td>{{ bloque.nombre }}</td>
                        <td>{{ bloque.carrera.nombre }}</td>
                        <td>  {{bloque.carrera.facultad.nombre}}</td>
                        <td>{{ bloque.descripcion }}</td>
                        <td class="text-center">
                            <a href="#" onclick="showAlert('{{ bloque.link }}')">
                                <i class="fas fa-eye"></i>
                            </a>
                        </td>
                        <td class="text-center">
                            {% if bloque.estado %}
                                <span class="text-success">Disponible</span>
                            {% else %}
                            <span class="text-danger">No dispobible</span>
                            {% endif %}
                        </td>
                        <td>
                            <div class="text-center d-flex flex-wrap justify-content-center">
                                <div class="mr-2 mb-2">
                                    <img class="rounded" width="50" height="50" src="{{ bloque.imagen.url }}" >
                                </div>
                            </div>
                        </td>
                        <td>
                            <div class="text-center">
                                <a href="">
                                    <i class="fas fa-trash-alt text-danger"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function showAlert(link) {
            Swal.fire({
                text: link,
                icon: 'warning',
                confirmButtonText: 'Ok'
            });
        }
    </script>
</div>



{% endblock %}

Vision360/core/templates/RestaurantBooking/PagesFacultades/carreras.html
{% extends 'RestaurantBooking/PageUtils/base.html'%}

{% block content%}
                    <div class="card shadow mb-4">
                        <div class="alert alert-warning">
                            <p>Para registrar una nueva carrera navega hasta el menú ubicado al lado izquiero <spam style="color: black;">(Gestión Carreras > Nueva carrera)</spam>, haz click,  llena el formulario y listo.</p>
                         </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead class="thead" style="background-color: #111927; color: aliceblue;">
                                        <tr>
                                            <th>Carrera</th>
                                            <th>Facultad</th>
                                            <th>Duración (semestres)</th>
                                            <th>Fecha Registro</th>
                                            <th>Estado</th>
                                            <th>Recorrido </th>
                                            <th>Opciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in carreras %}
                                        <tr>
                                            <td>{{ item.nombre }}</td>

                                            <td>
                                                {{item.facultad.nombre}}
                                            </td>
                                            <td>
                                                <div class="text-center">
                                                    {{item.semestres}}
                                                </div>
                                                </td>
                                            <td>{{item.date_joined}}</td>
                                            <td>Activo</td>                                                
                                            <td class="text-center">
                                                    {% if item.recorrido %}
                                                        <span class="text-success">Disponible</span>
                                                    {% else %}
                                                    <span class="text-danger">No dispobible</span>
                                                    {% endif %}
                                                </td>
                                            <td>
                                                <div class="text-center">
                                                    <a href="">
                                                        <i class="fas fa-trash-alt text-danger"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>

                    <script>
                        document.getElementById('toggleForm').addEventListener('click', function() {
                            var formDiv = document.getElementById('createForm');
                            if (formDiv.style.display === 'none') {
                                formDiv.style.display = 'block';
                            } else {
                                formDiv.style.display = 'none';
                            }
                        });
                    </script>
                    

{% endblock %}

Vision360/core/templates/RestaurantBooking/PagesFacultades/facultades.html
{% extends 'RestaurantBooking/PageUtils/base.html'%}

{% block content%}
                    <div class="card shadow mb-4">
                        <div class="end">
                            <div class="alert alert-warning">
                                <p>Para registrar una nueva facultad navega hasta el menú ubicado al lado izquiero <spam style="color: black;">(Gestión Facultades > Nueva facultad)</spam>, haz click,  llena el formulario y listo.</p>
                             </div>

                        </div>
                        <div class="card-body">
                            <div class="table-responsive">
                                <table class="table table-striped table-bordered" id="dataTable" width="100%" cellspacing="0">
                                    <thead class="thead" style="background-color: #111927; color: aliceblue;">
                                        <tr>
                                            <th>Facultad</th>
                                            <th>Siglas</th>
                                            <th>Ubicación</th>
                                            <th>Fecha Creación</th>
                                            <th>Estado</th>
                                            <th>Opciones</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for item in facultades %}
                                        <tr>
                                            <td>{{ item.nombre }}</td>
                                            <td>{{item.siglas}}</td>
                                            <td><a target="_blank" href="{{item.ubicacion}}"><button class="btn btn-success">Visitar <i class="fas fa-map-marker-alt"></i></button></a></td>
                                            <td>{{item.date_joined}}</td>
                                            <td>Activo</td>
                                            <td>
                                                <div class="text-center">
                                                    <a href="">
                                                        <i class="fas fa-trash-alt text-danger"></i>
                                                    </a>
                                                </div>
                                                
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            
                        </div>
                    </div>


{% endblock %}

Vision360/core/templates/RestaurantBooking/PagesFacultades/nueva-carrera.html
{% extends 'RestaurantBooking/PageUtils/base.html' %}

{% block content %}

<div class="modal-body">
    <div class="card-body border p-4 mt-4" id="createForm" style="margin: 0 auto; max-width: 500px;">
        <!-- Formulario de creación de carrera -->
        <form method="post" action="{% url 'registrar-carrera' %}" style="display: block;">
            {% csrf_token %}
            <h4 class="mb-4 text-center">Registrar Nueva Carrera</h4>
            <div class="form-group row">
                <label for="id_nombre" class="col-sm-3 col-form-label">Nombre:</label>
                <div class="col-sm-9">
                    {{ form.nombre }}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_semestres" class="col-sm-3 col-form-label">Semestres:</label>
                <div class="col-sm-9">
                    {{ form.semestres }}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_facultad" class="col-sm-3 col-form-label">Facultad:</label>
                <div class="col-sm-9">
                    {{ form.facultad }}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_recorrido" class="col-sm-3 col-form-label">Recorrido:</label>
                <div class="col-sm-9">
                    {{ form.recorrido }}
                </div>
            </div>
            <div class="text-center">
                    <button type="submit" class="btn btn-success">Guardar</button>
            </div>
        </form>
    </div>
    
</div>

{% endblock %}

Vision360/core/templates/RestaurantBooking/PagesFacultades/nueva-facultad.html
{% extends 'RestaurantBooking/PageUtils/base.html' %}

{% block content %}

<div class="modal-body">
    <div class="card-body border p-4 mt-4" id="createForm" style="margin: 0 auto; max-width: 500px;">
        <!-- Formulario de creación de carrera -->
        <form method="post" action="{% url 'registrar-facultad' %}" style="display: block;">
            {% csrf_token %}
            <h4 class="mb-4 text-center">Registrar Nueva Facultad</h4>
            <div class="form-group row">
                <label for="id_nombre" class="col-sm-3 col-form-label">Nombre:</label>
                <div class="col-sm-9">
                    {{ form.nombre }}
                </div>
            </div>
            <div class="form-group row">
                <label for="id_siglas" class="col-sm-3 col-form-label">Siglas:</label>
                <div class="col-sm-9">
                    {{ form.siglas }}
                </div>
            </div>
            <div class="form-group row">
                <div class="alert alert-danger">
                    <p >
                        En el el campo ubicación debes agregar en formato url la dirección de la facultad que estas creando
                    </p>

                </div>
                <label for="id_ubicacion" class="col-sm-3 col-form-label">Ubicación:</label>
                <div class="col-sm-9">
                    {{ form.ubicacion }}
                </div>
            </div>
            <div class="text-center">
                    <button type="submit" class="btn btn-success">Guardar</button>
            </div>
        </form>
    </div>
    
</div>

{% endblock %}

Vision360/core/templates/RestaurantBooking/PagesFacultades/nuevo-bloque.html
{% extends 'RestaurantBooking/PageUtils/base.html' %}


{% block content %}
<div class="container">
    <h2>Registrar Nuevo Bloque</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_codigo_identificativo">Codigo Identicativo:</label>
            {{ form.codigo_identificativo }}
        </div>
        <div class="form-group">
            <label for="id_nombre">Nombre:</label>
            {{ form.nombre }}
        </div>
        <div class="form-group">
            <label for="id_carrera">Carrera:</label>
            {{ form.carrera }}
        </div>
        <div class="form-group">
            <label for="id_descripcion">Descripción:</label>
            {{ form.descripcion }}
        </div>
        <div class="form-group form-check">
            {{ form.estado }}
            <label class="form-check-label" for="id_estado">Estado</label>
        </div>
        <div class="form-group">
            <label for="id_imagen">Imagen:</label>
            {{ form.imagen }}
        </div>
        <div class="form-group">
            <label for="id_link">Link:</label>
            {{ form.link }}
        </div>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}